import os

"""
This file defines outputting Flowchart as html.

This is straight up https://github.com/adrai/flowchart.js/blob/master/example/index.html
with minor color and size changes.
Use of this source code is governed by a MIT
license that can be found in https://github.com/adrai/flowchart.js/blob/master/license
To keep it simple this is a sandwich of html.
Top header
<insert title>
Rest header into body html until you get to code block
<insert code block>
Remainder body of html closing up the code block, adding couple buttons, and canvas generated by code block.
"""
def output_html(output_name: str, field_name: str, flowchart: str) -> None:

    # Three raw html code sections encapsulated in triple quotes """
    html_part_before_title="""<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>"""
    html_part_after_title_before_code_block="""</title>
        <style type="text/css">
          .end-element { fill : #FFCCFF; }
        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/js/bootstrap.bundle.min.js"></script>
        <!-- <script src="../release/flowchart.min.js"></script> -->
        <script>

            window.onload = function () {
                var btn = document.getElementById("run"),
                    cd = document.getElementById("code"),
                    chart;

                (btn.onclick = function () {
                    var code = cd.value;

                    if (chart) {
                      chart.clean();
                    }

                    chart = flowchart.parse(code);
                    chart.drawSVG('canvas', {
                      'x': 0,
                      'y': 0,
                      'line-width': 3,
                      //'maxWidth': 15,//ensures the flowcharts fits within a certain width
                      'line-length': 50,
                      'text-margin': 10,
                      'font-size': 14,
                      'font': 'normal',
                      'font-family': 'Helvetica',
                      'font-weight': 'normal',
                      'font-color': 'black',
                      'line-color': 'black',
                      'element-color': 'black',
                      'fill': 'white',
                      'yes-text': 'yes',
                      'no-text': 'no',
                      'arrow-end': 'block',
                      'scale': 1,
                      'symbols': {
                        'start': {
						  'font-size': 14,
                          'font-color': 'yellow',
                          'element-color': 'blue',
                          'fill': 'green',
						  'class': 'start-element'
                        },
                        'inputoutput': {
                          'font-color': 'black',
                          'element-color': 'black',
                          'fill': 'bisque'
                        },
                        'operation': {
                          'font-color': 'black',
                          'element-color': 'black',
                          'fill': 'linen'
                        },
                        'subroutine': {
                          'font-color': 'black',
                          'element-color': 'blue',
                          'fill': 'lightgreen'
                        },
                        'condition': {
                          'font-color': 'red',
						  'element-color': 'black',
                          'fill': 'yellow'
                        },
                        'end':{
						  'font-size': 20,
                          'class': 'end-element'
                        }
                      },
                      'flowstate' : {
                        //'past' : { 'fill' : '#CCCCCC', 'font-size' : 12},
                        //'current' : {'fill' : 'yellow', 'font-color' : 'red', 'font-weight' : 'bold'},
                        //'future' : { 'fill' : '#FFFF99'},
                        'request' : { 'fill' : 'blue'},
                        'invalid': {'fill' : '#444444'},
                        'approved' : { 'fill' : '#58C4A3', 'font-size' : 12, 'yes-text' : 'APPROVED', 'no-text' : 'n/a' },
                        'rejected' : { 'fill' : '#C45879', 'font-size' : 12, 'yes-text' : 'n/a', 'no-text' : 'REJECTED' }
                      }
                    });

                })();

            };
            function myFunction(event, node) {
              console.log("You just clicked this node:", node);
            }
            
        </script>
		<script>
			function HelpText() {
			  var x = document.getElementById("HelpTextBlock");
			  if (x.style.display === "none") {
				x.style.display = "block";
			  } else {
				x.style.display = "none";
			  }
			}
		</script>
    </head>
    <body>
        <div><textarea id="code" style="width: 100%;" rows="11">"""

    html_part_after_code_block_remaining_html="""</textarea></div>
        <div><button id="run" type="button">Run</button> <button onclick="HelpText()">Format Help</button></div>
        
		<div id="HelpTextBlock" style="display:none">Conditions can also be redirected like cond(yes, bottom) or cond(yes, right)
... and the other symbols too... like sub1(right)<br/>
You can also tweak the diagram.drawSVG('diagram', {}); script in this file for more changes<br/>
This is based on <a href="https://github.com/adrai/flowchart.js">flowchart.js on github</a> and <a href="http://flowchart.js.org">http://flowchart.js.org</a> more documentation can be found over there.
</div>

        <div id="canvas"></div>
    </body>
</html>"""
    # No checking or prompting if output file already exists.
    # This will overwrite if given an existing output file
    with open(output_name, 'w') as f:
        # html_part_before_title is header before <title>, 
        f.write(html_part_before_title)
        # If field specified use that as title. If not, use output filename as title.
        if bool(field_name):
            f.write(field_name)
        else:
            f.write(os.path.basename(f.name))
        # Output remainder of header up to the flowchart code block (html_part_after_title_before_code_block)
        f.write(html_part_after_title_before_code_block)
        # Output the flowchart into the code block section of the html
        f.write(flowchart)
        # Output the remainder of the html. (html_part_after_code_block_remaining_html)
        # End code block. Add couple buttons. Add output canvas.
        f.write(html_part_after_code_block_remaining_html)
        # Print to console confirming to end user it was saved.
        print(f"Saved HTML to {output_name}")
